
# Echo
POST http://127.0.0.1:7071/echo HTTP/1.1
content-type: application/json

{
  "message": "Hello World!"
}

###

# Order
POST http://127.0.0.1:7071/order HTTP/1.1
content-type: application/json

{
  "id": 1005,
  "quantity": 2,
  "color": "black"
}